- app/src/main/java/com/kamron/pogoiv/MainActivity.java
extraced method "checkPermissions" & finalized not changing parameters
> Refactored MainActivity

- app/src/main/java/com/kamron/pogoiv/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
> pretty print java

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/res/layout/activity_main.xml
no need to do this by hand every time
> version number now loaded dynamically

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
added german translation and a ´ on top of the e of Pokémon
> Localization welcome screen

- .idea/.name
- .idea/compiler.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- app/build.gradle
- app/src/main/java/com/kamron/pogoiv/pokefly.java
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/values/colors.xml
- build.gradle
I moved the info layout to an XML file in order to reduce the amount of java code in pokefly.java.
Also added [ButterKnife](http://jakewharton.github.io/butterknife/) to make it more readable.
> Refactored createInfoLayout

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
> Pokemon Go should now open on clicking the start button

- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
> added translation for dialog info window

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
Hello,
This is a new request to select a pokemon base from the candies instead of the name of the pokemon when is not found.
- Please check the rectangle and color of the ocr (I let a TODO).
- I've check if the name of the pokemon is perfect to a pokemon name. will be better to allow a little of tolerance.
Oliver, Pogo trainer.
> Selection of the pokemon base on the candies instead of the name of the pokemon

- app/src/main/java/com/kamron/pogoiv/CPRange.java
- app/src/main/java/com/kamron/pogoiv/IVCombination.java
- app/src/main/java/com/kamron/pogoiv/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/UpgradeCost.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
Makes the pokefly methods more readable, by having other classes handle iv calculations and such.
> Refactor of pokefly, crash solution for when no cp detected & improved cp detection

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
> Adds a method to gender nidorans

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/ShareHandlerActivity.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
- app/src/main/res/layout/activity_share_handler.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
Fixed up my earlier pull requests and pushing them again.
I also addressed comments made on the earlier pull request for the evolution tracking. The code no longer assumes any relation between pokemon and their devolutions.
> Improve efficiency of evolution tracking and Google now support

- app/src/main/java/com/kamron/pogoiv/CPRange.java
- app/src/main/java/com/kamron/pogoiv/IVCombination.java
- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/UpgradeCost.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
I like immutability, especially if all the fields are going to be public.
There's a good argument to be made to go with private and getters but that's a bigger change
> made data fields on the model classes final where possible

- app/src/main/java/com/kamron/pogoiv/IVCombination.java
- app/src/main/java/com/kamron/pogoiv/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/ScanContainer.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
gastly crash fix
Landscape crash fix
IV intersection logic
> Crashfixes and IV intersection logic

- app/src/main/java/com/kamron/pogoiv/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
With these changes, a Wartotle49 is detected as Wartortle rather than Squirtle, and so on for all evolved & renamed pokemons.
> Improve Pokemon detection on mismatches

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
Taken with credit from bc9bb85aed2902ea61fccbc71afd9a32c9f40991.
I've updated the refactoring for the new code: where code added new
magic strings, I've turned them into constants too.
> refactor service

- DEVELOPMENT.md
I just took a while to discover this project needs the latest SDK since
it uses Java 8.
> Dev. docs: Specify required versions

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/res/values/strings.xml
- gradle.properties
These seem too small for separate PRs.
> Miscellaneous changes

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/values/strings.xml
There are two main usability/UX problems solved here:
1. There was no difference between 100% match in name and suspicious (probably wrong) name recognition. -> In this pull request you get a green/yellow/red indicator of similarity.
2. There was no quick way of of correcting entered values. -> Added back button.
Kind of related to Issue #24 
This is a replacement for my previous pull request #106
>  Info dialog ux related to invalid input data

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/PokemonSpinnerAdapter.java
* pokemon list adapter with pokedex-index
* don't sort pokedex
* set candy name if the matched is better
I believe this resolves Issue #24
> Selection better suited for candy matched pokemons

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdate.java
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdateDialog.java
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdateDownloader.java
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdateEvent.java
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdateLoader.java
- app/src/main/java/com/kamron/pogoiv/updater/SemVer.java
Hi! I implemented auto update, using code from PokeScanner. It looks like this:
It should be fine but please double check result :)
> Impliment auto update

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Changes evolution CP estimate from trainer max level to pokemon current level
Bolds the Min avg max line
> Tweaks to the results panel

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
If the pokemon name match isn't good, we can't just pick the pokemon
name that matches the candy name perfectly. If the candy name was
detected perfectly, then we'll always end up picking the base pokemon.
Instead, once we figure out the base pokemon with the best candy name
match, we have to go through all the pokemon with that candy name and
see how well they match with the detected pokemon name.
> Fix candy name based Pokemon search

- DEVELOPMENT.md
My Android Studio did not understand notations until I installed the plugin.
> Add instructions for lombok

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
This is a loop that does a single iteration because it always breaks.
That's silly.
The most robust solution is to keep the loop (see discussion in
https://github.com/farkam135/GoIV/pull/144#issuecomment-241709760).
Fixes #144.
> Cleanup loop

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Moved the battery saver option from the MainActivity to the settings page. Also updated the instructions regarding the battery saver.
> Moved battery saver

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/PokemonSpinnerAdapter.java
Reverts farkam135/GoIV#159. Decide on how we want to display the spinner.
> Revert "Narrows down spinner options to candy evolution line"

- app/src/main/java/com/kamron/pogoiv/IVCombination.java
- app/src/main/java/com/kamron/pogoiv/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
Average % rounded
Only min/max IV shown
Current level evolution CP estimate instead of trainer max
> Solves 3 of the "bloat issue" things

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/ShareHandlerActivity.java
- app/src/main/res/values/strings.xml
This PR fixes #135. The various bugs are described in commit messages. There are a few refactorings at the beginning which I did while reviewing possibly relevant code.
> Fix IV button disappearing and GoIV crashing on stop

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/res/values/strings.xml
Also fixed a small grammatical error in the settings page. Fixes #176
> Call openPokemonGoApp also in snapshot mode

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Most of the regions of the image that need OCR don't change often across
different times the same pokemon is analyzed. Things like name and candy
name are even common across different pokemon. So, we can safely cache
the results of OCRing these images.
To save memory, we cache the results using a hash of the image and not
the entire image.
The CP image changes a lot due to changing background. So, there's not
much of a point to cache it. So, we don't cache OCR results for the CP.
Profiling of this code showed that the caching operation takes about
1-3 milliseconds. Whereas OCR takes from 50-260 milliseconds depending
on the image being OCRed. So, this change definitely bring in a lot of
performance and power saving benefits.
> Cache OCR results for parts of the bitmap that don't change often

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Fix typo error in the code. Luckily PokeyFly existed only in MainActivity.
> PokeFly not PokeyFly

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Fix #188. Untested.
@oskomonzon / @MalkavSoft can you try this out? (Gotta fix master meanwhile).
> Quickfix candy detection for Spanish

- app/build.gradle
- app/src/main/java/com/kamron/pogoiv/updater/AppUpdateLoader.java
When making a new version, you need to update all three versionName variables in the build.gradle file. Also,the string "(Offline)" should be present in two places :
1) The versionName variable in the offline closure in the build.gradle file and
2) The tag name in the GitHub release of the offline version
Fixes #172
> Made adjustments for offline release

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Initial set of commits I'd like to merge. I'll proceed to clean this up further.
> Move OCR code to separate class

- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/expanded_results_box.xml
Quick fix addressing #214 
It looks way better.-
> White background color on spinner popups

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
> Multiple small fixes

- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
Fixed the improper cutting of candy bitmap and made change that skips a ton of math. replaceColors() should be much faster now.
> Optimize ocr

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_results.xml
- app/src/main/res/values/strings.xml
Capitalise 'I' in Information for consistency
Replace BLACK RIGHT POINTING POINTER to BLACK RIGHT POINTING TRIANGLE so both triangles are the same
> Fix Advanced Info and Triangle

- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
This fixes the crash noticed on Crashlytics for 3.0. I have more cleanups on this code, but I'd leave figuring out the root cause for next release.
> Quickfix for crash

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/dialog_results.xml
- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/values/styles.xml
Lots of small changes. Adding a screenshot.
> Theme rework and minor aesthetics fixes

- app/src/main/java/com/kamron/pogoiv/Data.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
If there were rounding bugs this might also fix them. I'm especially afraid of some doubles that were truncated down and rounding errors, though in theory the old code should work...
> Simplify arc formula

- app/src/main/res/values-it/strings.xml
Hi all!
This is my first pull request, so let me introduce myself: I'm an italian Android developer addicted to Pokémon GO. I've got a couple of ideas that could be merged into this app but I thought it would be better to start with a simple translation!
So here's my values-it/strings.xml file.
I've tested it: the app builds and the app layouts don't brake.
I hope it meets your standards!
Mattia
> Add italian translation.

- DEVELOPMENT.md
Easy step-by-step guide
Includes commonly faced issues with Lombok IntelliJ Plugin and Annotation Processing
Includes Syncing of fork for new GitHub users
> Rewrite DEVELOPMENT.md

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Reverts #264 as it doesn't compile.
> Revert "refactor settings so that reads always return the current value"

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/online/java/com/kamron/pogoiv/CrashlyticsWrapper.java
https://github.com/farkam135/GoIV/pull/264 with online mode working too
:facepalm:
> refactor settings so that reads always return the current value

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/drawable/spinner_color_set.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/spinner_evolution.xml
Fixes #274 & addresses partially #273.
- Advanced Information's Evolution spinner is now disabled if there isn't another option to pick. Text color while disabled matches regular text now, merging it seamlessly with the rest of the information.
- Replaced Main Activity's Trainer Level EditView with a NumericPicker.
> Small UI improvements

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
Cost information taken from http://pokemongo.gamepress.gg/power-up-costs
> Correct upgrade cost after lvl 26.

- app/src/main/java/com/kamron/pogoiv/DevMethods.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/PokemonSpinnerAdapter.java
- app/src/main/java/com/kamron/pogoiv/ScanContainer.java
- app/src/main/java/com/kamron/pogoiv/logic/CPRange.java
- app/src/main/java/com/kamron/pogoiv/logic/Data.java
- app/src/main/java/com/kamron/pogoiv/logic/IVCombination.java
- app/src/main/java/com/kamron/pogoiv/logic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/logic/Pokemon.java
- app/src/test/java/com/kamron/pogoiv/IVCombinationTest.java
Goal: separate core logic from GUI logic. That's just a step to clarify which is which.
I also hope this helps writing unit tests (though @harkin already contributed a way to mock Android, not sure how well that works).
Thoughts?
(Let's be careful with merging this and conflicts on other PRs).
> Move game logic into separate package

- app/build.gradle
- app/src/main/java/com/kamron/pogoiv/IVResultsAdapter.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_all_possibilities.xml
- app/src/main/res/layout/iv_results_item.xml
- app/src/main/res/values/strings.xml
Made a series of changes that fix #280 
All results layout now displays data in a RecyclerView. This is way more efficient and should reduce the choppyness of the UI in cases where there is a results overload.
Most of the work is done in a new custom Adapter, so I got rid of some of the stuff from Pokefly that shouldn't be needed anymore.
Headers now support localization (used the same strings as in other layouts, added just one new for the percentages column).
That's from the top of my head. I tweaked things here and there but nothing too crazy.
So there you have it. Pending review. :+1:
> Reworked All Results UI

- app/src/main/java/com/kamron/pogoiv/GUIUtil.java
- app/src/main/java/com/kamron/pogoiv/IVResultsAdapter.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
New GUIUtil class to avoid code duplication addressing the issue with my previous PR.
> New GUIUtil class to eliminate code duplication

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
Some minor strings jazz:
1. Spanish strings update.
2. Removed "-" from powerup_calc_instructions.
3. Replaced "Powerup" for "Power up" in powerup_calc_instructions.
> Spanish strings update and minor string fixes.

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Fixes #295. <s>Under testing</s> Appears to work. Review by @sarav.
> Remember text distance in pokemon name correction cache

- app/src/main/java/com/kamron/pogoiv/IVResultsAdapter.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/res/layout/autocomplete_pokemon_list_item.xml
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/dialog_input_poke_picker.xml
- app/src/main/res/layout/dialog_results.xml
- app/src/main/res/values/strings.xml
The start of the solution for #130 . 
This allows the user to pick pokemon by either the dropdown, which is now only 1 evolution chain instead of the entire pokedex, or by searching for the pokemon name in an autocompletetextview.
I know the button is not the nicest looking thing, but I'd like people to test the functionality.
> Pokemon dropdown selector / autocomplete textview on inputscreen

- README.md
PR does the following:
* Sync README with Reddit wiki (adds the comic)
* Update README to 3.1.0
* Update CHANGELOG to 3.1.0
> Update README.md and CHANGELOG.md to 3.1.0

- CHANGELOG.md
- README.md
PR actually updates CHANGELOG. Minor changes to README.
> Update README and CHANGELOG 3.1.0

- app/src/main/java/com/kamron/pogoiv/DevMethods.java
- app/src/main/java/com/kamron/pogoiv/FontsOverride.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/PoGoApplication.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/ScreenGrabber.java
- app/src/main/java/com/kamron/pogoiv/logic/Data.java
- app/src/main/java/com/kamron/pogoiv/logic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanContainer.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanResult.java
- app/src/main/java/com/kamron/pogoiv/logic/UpgradeCost.java
- app/src/main/java/com/kamron/pogoiv/widgets/IVResultsAdapter.java
- app/src/main/java/com/kamron/pogoiv/widgets/PokemonSpinnerAdapter.java
This is me starting to read the code and fix nonsense.
Non-obvious goals:
- stuff that mutates state can be hard to follow, so try to *not* hide where this happens. A constructor of a data object like `IVScanResult` changing state is *bad*.
- reduce "action at a distance". If something is set in a place and used somewhere else entirely, it's hard to follow what's happening.
- if a function computes some result, it shouldn't return it by storing it in fields that are used later—if you do that, somebody can break the code by reordering calls that seem unrelated.
> First bunch of refactorings

- app/src/main/res/values-pt/strings.xml
Was just a small grammar error.
> Fix grammar in Portuguese translation

- DEVELOPMENT.md
Fix mix up of versionCode and versionName
> DEVELOPMENT.md: Fix mix up of versionCode and versionName

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/IVScanResult.java
- app/src/main/res/layout/dialog_input_appraisal.xml
- app/src/main/res/layout/goiv_spinner_item.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Most of the changes were discussed with @nahojjjen. Things are looking good :+1: 
I tweaked a little the logic replacing the if chains for switch. Also got rid of the gap at 81% just in case.
It looks something like this:
> Spanish localization and UI improvements for appraisals

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
PokemonNameCorrector is large enough for its own class, also because it has its own state. This would also help with the refactoring.
I wasn't sure what interface I should have, so I've added a few options. One even uses Lombok. What do you think?
Untested yet.
> Split out PokemonNameCorrector from Pokefly

- app/src/main/res/values-fr/strings.xml
I translated the new appraisal-related strings, and tested it on my phone for each team. It looked good.
> Update French localization for more appraisal

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanContainer.java
Fix #383 and clarify the involved code, since it was clearly rather confusing.
> Fix evolution check and revise code

- app/src/main/java/com/kamron/pogoiv/GUIUtil.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/widgets/IVResultsAdapter.java
Use text color based on Appraisal system.
> Color IV based on appraisal thresholds

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/ScreenShotHelper.java
Moved all ScreenShot handling code into a separate class. This also fixes battery saver mode not working for a lot of devices (surprisingly, there's not issue for this. Or at least I couldn't find one).
Also fixes #325 indirectly.
> Refactor and clean up ScreenShot handling code and improve device support

- app/src/main/res/values/strings.xml
Just a few things I missed in #379.
> Minor text fixes

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Add empty on touch listener to prevent changes to seekbar thumb 1
Fix #412
> Fix movable background seekbar

- CONTRIBUTING.md
- README.md
Add badges. They make README look awesome, thanks shields.io!
Download link will always be /release/latest as both Online and Offline apks can be found there
Need feedback on download and changelog (version) badge. Will people feel like they are buttons that lead to release page or changelog page?
> Update README - Add more badges, link to CONTRIBUTING.md

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Following the discussion at PR #418
Should work as intended now.
> Ensure soft keyboard does not obstruct layout

- README.md
According to the answer I got in issue #424, this is a common question, so it should go in the FAQ for visibility.
Fix #424
> Add PoGo black screen issue to FAQ section

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
> Register button handler after completing setup

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Fix #223, and refactor code.
Lots of this is based on #416 by @nahojjjen, especially most of the refactorings with their comments, but I end up with slightly different code, especially for `initSpinnerIfNecessary`.
> Auto select evolution for estimate v2

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- checkstyle/android/content/annotations.xml
Split out from #430. Gonna merge based on the existing review there.
> Improve handling of snapshot path and fix bugs with it

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Updating #404 to avoid some UI twitches and clean up the intents a bit.
EDIT: to summarize:
> This adds the "Open app" and "Stop" actions and improves the overall notification style and attributes on latest Android versions.
Closes #404.
Supersedes #371 (its first version).
Fixes #268.
> Add actions to notifications, V3

- CHANGELOG.md
The changelog is based on @nahojjjen's, but he said we might want to take another look.
> Prepare for releasing 3.2

- app/src/main/res/values-fr/strings.xml
I translated the new strings displayed in the notification, and the "accept screen capture" one.
> Update French localization (notification actions)

- app/src/main/res/values-es/strings.xml
EDIT: All good now. Feel free to merge xD
I decided to translate the new place1 and place2 strings in a less literal way because otherwise it would sound really odd in spanish.
"Choose overall phrase:" as "Sobre el Pokémon en su conjunto…" (About Pokémon's overall...)
"Choose stats phrase:" as "Sobre sus características…" (About his stats...)
Mainly because semantics. Should be easy to understand anyway.
> Spanish strings update

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
added german translation as asked for https://github.com/farkam135/GoIV/issues/447 and marked "unknown_percent", "iv"& "percent" as untralatable
also 	changed "autodetecting" to "auto detecting"
> Added german translation

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
> Refactor setup of Nidoran names

- app/src/main/res/values-fr/strings.xml
valoriv15 and valoriv13_14 were swapped
> error with team valor french translation

- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
I translated the new strings added by #469.
> Update French localization

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
> Info overlay defaults to appraise box closed

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Refactoring to support #431. (Untested).
> Generalize replaceColors

- app/src/main/res/values-fr/strings.xml
I translated the new PokeSpam-related strings and tested it on my phone.
> Update French localization (PokeSpam)

- build.gradle
Android Studio was updated to 2.2.1 and Gradle was updated as well.
> Update Gradle to 2.2.1

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/layout/goiv_spinner_item.xml
- app/src/main/res/layout/spinner_appraisal.xml
- app/src/main/res/values/styles.xml
Attempt to fix #475
NOTE: THIS IS YET TO BE TESTED! DO NOT MERGE!
@thearaks require your testing on your 4.4 device
Tested on 6.0.1, and don't see any changes (except for the font change), or having any crashes. This is just to test if it crashes on 4.4, any unintended minor UI changes only to be fixed after the crash is fixed on 4.4.
> Attempt to fix appraisal refining crash on 4.4 devices

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanResult.java
Supersedes #408 and #431. I rebased #431 on master, used the new version of `replaceColors` and added Checkstyle fixes.
EDIT: Fixes #381.
> Candy cost identification v3

- build.gradle
Android Studio bugged me about this when I opened the project
> updated gradle build tools to 2.2.2

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Also changes the cropping to a new wrapping method which is easier to
read & tweak
> Fixes crop misalignments for pogo update

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardModifierActivity.java
- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenButton.java
- app/src/main/res/layout/activity_clipboard_modifier.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Moves the clipboard configuration from the main activity to the settings
Tweaks several things in the clipboard configuration, it's messier but explains more.
Edit: fixes #526
> Clipboard UI upgrade

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Previous "upgrade cost" scan  kinda broke in some cases with new pogo update & new scanning cropping parameters. This should fix those issues.
> Updates the upgrade cost scanning parameters

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/NpTrainerLevelPickerListener.java
This PR will Restart GoIV when selecting level.
Once #499 is finished we can reuse commit https://github.com/farkam135/GoIV/commit/656e8e7f66f5e9a66b15cba730b236af086348d5 code to change the Trainer Level (since we will not stop/start we don't need to start Pokemon Go App)
> Restart GoIV after choosing level

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
Minor coding style fixes. (I'd usually merge directly on master but I decided I'd better be more careful).
> Coding style fixes

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/drawable/ic_add_white_24px.xml
- app/src/main/res/drawable/ic_pause_white_24px.xml
- app/src/main/res/drawable/ic_play_arrow_white_24px.xml
- app/src/main/res/values/strings.xml
Switches the icons for play / pause and add in the notification to material design ones.
This changes the "Stop" icon to a "pause" icon, which I motivate with that we've changed the behaviour of the button since the stop icon was picked, and that button actually just pauses GoIV now.
> Update icons in notification

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
1. Moved candy image higher and longer
2. Reduced replaceColors range
> modified candy scanning area to fix scanning for some users

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Tweaks the scanning parameters for candy and cp to handle errors users have encountered.
> Hotfixes for scanning errors

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/CreditsActivity.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
- app/src/main/res/layout/activity_credits.xml
- app/src/main/res/layout/content_credits.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/settings.xml
Several terms of open source projects require that you link back to the source somewhere in the app, and it's also the nice thing to do. So while this is not a feature or bugfix, it's still something that's required in the app.
edit: fixes #328
> Adds credit activity accessible though settings

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/LevelUnicodeToken.java
Adds a token to the clipboard list which just shows the number as a unicode + half unicode.
> Adds unicode level token

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
App no longer records manual user corrections for pokemon names
> Removes the userCorrection implementation

- app/src/offline/java/com/kamron/pogoiv/updater/AppUpdateUtil.java
Adds a method stub for deletePreviousApkFile so offline build can
compile
> Fixes compile error for offline version

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Use a single instance initiated in onCreate.
> Refactor settings in PokeFly

- app/build.gradle
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt/strings.xml
This was the gradle changes i did for the 3.3.2 release, which I forgot to upload.
> Releasestuff

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Implemented algorithm starts at the center point of each candidate level, then searches for consecutive white pixels up, down, left, and right. By comparing how far we can travel in all directions with only white pixels, we can more accurately determine if the proposed center is the true center of the onscreen dot.  This helps significantly with level 30.0+ detection.
> Modified level detection algorithm to better handle L30+

- app/src/main/res/values/strings.xml
Re-adds the word "not" in the "not out of the norm" phrase.
> Adding "not" to "out of the norm" to match phrase from Blanche

- app/src/main/res/values/integers.xml
Updates to the evolutionCandyCost for each of the Gen 2 Pokemon.
Any values that have not yet been confirmed are marked as TODO: CONFIRM
All others were verified via the PoGo app or reddit screenshot.
> Update Gen2 evolutionCandyCost

- app/src/main/res/values-es/strings.xml
Updated strings of spanish in "values-es" and updating with new strings added of the original "strings.xml" file.
> Strings in spanish up to date

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardModifierActivity.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/BaseStatToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/CpPercentileToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/CpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/ExtendedCpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/HexIVToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/HpToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/IVSum.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/LevelToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/LevelUnicodeToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/PerfectionCPPercentageToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/PokemonNameToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/PowerupsToMaxToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/UnicodeToken.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
Also tweaks the introductiont text on the main startup page, making it
left aligned.
> Removes mention of Pokemon from eng strings

- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/ExtendedCpTierToken.java
This pull request changes the behavior of the ExtendedCpTierToken in case multiple evolution lines are available for a selected Pokémon. In accordance with the spirit of the initial proposal of ordering Pokémon by how promising in terms of CP they are, the system now computes the best possible outcome out of all the possible evolution branches.
For instance, with this change, Eevee's projected CP at maximum evolution will use Vaporeon's stats (rather than Umbreon's), Poliwag will match with Poliwrath (not Politoed), Oddish with Vileplume, and so on.
> Use the evolution with higher CP

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Pretty dirty patch, but seems to let S8 scan the pokemon screen.
> Samsungs8patch

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/widgets/IVResultsAdapter.java
- app/src/main/res/layout/iv_results_item.xml
by clicking a row in the "all iv results" screen.
> Adds feature to copy single iv res to clip by click

- app/build.gradle
- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Adds a quick iv preview toast when viewing pokemon, which can be toggled off in settings
> Quickivpreview

- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Hi everyone!
Here is the updated italian localization.
I hope it will be ok!
Have a nice weekend!
> Italian translation v2

- app/src/main/java/com/kamron/pogoiv/logic/PokemonShareHandler.java
This exposes IV combinations to third party apps via the share button
on the results screen.
> Add IV combinations to shared results JSON

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Portuguese has "doces" (candy) coming first in candy name.
> Fix recognition of portuguese candy names

- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/WorthTrainingToken.java
After Travis resurgence, it discovered some code style issues in this class.
Fix them!
> Fix code style in WorthTrainingToken.java

- app/src/main/res/values-es/appraisals.xml
- app/src/main/res/values-es/strings.xml
Updated again the strings.xml in values-es with new strings translated, fixed old incorrect words and add and correct the appraisals.xml file from the branch "addSpanishAutoAppraisal"
I would have wanted to translate all the strings, like the show quick iv preview or others new but they are not yet in the values strings.xml to see the names of the strings
Ah, and this translation does not contain any dick jokes :P
> Updated spanish and added appraisals.xml

- app/src/main/res/values/integers.xml
Mewtwo's stats changed in the latest game_master.
Game_master: 0000015DDA542FC3_GAME_MASTER
Timestamp: 1502606536643
See https://www.reddit.com/r/TheSilphRoad/comments/6tgafs/mewtwos_base_stats_was_changed_in_the_latest_game/
> Update Mewtwo's stats

- app/src/main/res/values-es/appraisals.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Update spanish traduction, fixed minor texts, extract 2 hardtexts in settings to strings and other tweaks
> Updated spanish and other tweaks

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
when using android studio with this project all the time I get the notice to update the version of gradle and I have decided to modify it so that it is updated
> Update gradle to last version in Android Studio

- app/src/main/java/com/kamron/pogoiv/activities/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/GoIVNotificationManager.java
- app/src/main/java/com/kamron/pogoiv/widgets/PlayerTeamAdapter.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Small tweaks here and there and many hardcoded texts moved to string resources.
> Refresh start page improvements

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/BaseStatToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CPMaxToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CPMissingAtFourty.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CustomSeparatorToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/ExtendedCpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/HpToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/LevelToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/LevelUnicodeToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/PokemonNameToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/PowerupsToMaxToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/WorthTrainingToken.java
- app/src/main/java/com/kamron/pogoiv/widgets/recyclerviews/adapters/viewholders/TokenHeaderViewHolder.java
- app/src/main/res/layout/activity_ocr_calibration_result.xml
- app/src/main/res/values/strings.xml
- Revert change in tools:text L43 from activity_ocr_calibration_result.xml
- Extract names tokens to strings.xml
- Fix english tips
> Corrections and other tweaks in tokens and strings

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_all_possibilities.xml
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/dialog_refine_by_last_scan.xml
- app/src/main/res/layout/dialog_results.xml
- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/layout/fragment_clipboard_modifier.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
- Implemented an error warning when entering bad pokemon data and there is no IV result to help the user
- Revert change in android:text L44 from fragment_clipboard_modifier.xml
- Extracted hardcoded texts "MIN" & "MAX" from dialog_results.xml to strings.xml
- Optimized dialog_results.xml with many tweaks and added the new textview (correctCPLevel)
- Many tweaks in Pokefly.java
- Deleted string "too_many_iv_combinations" from all strings.xml files because it was no longer used
- Translated news strings and improved others of values-es
> Implemented error warning and others tweaks

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/activities/CreditsActivity.java
- app/src/main/res/layout/content_credits.xml
- app/src/main/res/values-v23/styles.xml
some fixes in creditsActivity and add opencv in list of credits
> little fixes for creditsActivity

- README.md
I changed the screenshots that were too old and I put new ones that show the current design of GoIV
And little fix in L49
> updated images & small fix in README

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocator.java
- app/src/main/res/layout/notification_pokefly_paused.xml
- app/src/main/res/layout/notification_pokefly_paused_expanded.xml
- app/src/main/res/layout/notification_pokefly_started.xml
- app/src/main/res/layout/notification_pokefly_started_expanded.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values-v24/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
A couple of minor bugs squashed.
Please merge only **after** #759!
Thank you!
> GoIV 4.0.0 bug fixes, second batch

- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- Fix a crash in the email client on missing read permission of attachment URI
- Improve email body
> Small improvements for emailRecalibrationFail branch

- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
> Add device maker, model and OS version to calibration error email

- app/src/main/java/com/kamron/pogoiv/activities/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
https://drive.google.com/open?id=0B8YGb9eCs7lQMWpiVUlLUVIycEE
> Fixed black screen when starting GoIV with PokemonGo started

- app/src/main/java/com/kamron/pogoiv/updater/DownloadUpdateService.java
Needs some testing on higher version before merging. Also, thearaks suggested
"We could also try with getExternalStoragePublicDirectory() instead getExternalFileDir() to avoid file permissions issues"
> Uses different non-crashing update logic on android < N

- app/src/main/res/xml/settings.xml
Was 'true' in GoIVSettings.class but not in settings.xml
> Fix autoUpdateEnabled default value

- .gitignore
Finally ignored DS_Store files when doing git status
currently with git status
now with this change
> fixed the infinite list of DS_Store files

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeSpam.java
- app/src/main/res/values/strings.xml
> improved pokespam result

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/MixedUnicodeToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/UnicodeToken.java
> clarify names of UIV tokens

- app/src/main/res/drawable/dot.xml
> Correct the size of dot arc

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
update gradle tool to 3.0.1
update gradle to 4.3.1
https://docs.gradle.org/4.3.1/release-notes.html
update google maven repo to google() as oficial announcement
https://developer.android.com/studio/build/dependencies.html#google-maven
change apt to annotationProcessor (android-apt deprectated)
https://bitbucket.org/hvisser/android-apt/wiki/Migration
update lombok and change the dependency as
`dependencies {
compileOnly "org.projectlombok:lombok:1.16.18"
}`
https://projectlombok.org/setup/android
update butterknife to 8.8.1 version
https://github.com/JakeWharton/butterknife
update guava to 23.5 version
https://github.com/google/guava/releases
add flavors dimens in ProductFlavor (now is required)
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#flavor_dimensions
> update graddle tool and others libraries (gradle 4.3.1, lombok 1.16.18, butterknife 8.8.1)

- app/src/main/res/values/integers.xml
Groudon and Slaking got nerfed on gen 3 release, this fixes that.
> Fix updated stats

- app/src/androidTest/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocatorTest.java
- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocator.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldNames.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldResults.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
- app/src/main/res/values/strings.xml
Calibrate and scan Pokémon power up stardust and candy costs
> Power up cost detection

- app/src/androidTest/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocatorTest.java
- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/PokemonGenderToken.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPreviewPrinter.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocator.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldNames.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldResults.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanContainer.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
- app/src/main/res/values/strings.xml
Implements feature request #816
Please merge only after #828
> Gender clipboard token

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/MainActivity.java
- app/src/main/res/color/goiv_btn_colored_borderless_text_material.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_ocr_calibration_result.xml
- app/src/main/res/layout/dialog_info_window.xml
- app/src/main/res/layout/dialog_input_poke_picker.xml
- app/src/main/res/layout/notification_pokefly_paused_expanded.xml
- app/src/main/res/layout/notification_pokefly_started_expanded.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/styles.xml
- Improve themes and styles in `values/styles.xml` and `values-v21/styles.xml`
- Improve styles usages for buttons and image buttons around the app
- Add touch feedback to many buttons that were "flat", especially image buttons
Fixes #809 #831
> Improve GoIV theme, styles and style usages in layouts

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/activities/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
Also improve calibration-related user warnings in MainActivity.
> Add screen calibration versioning

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
For stardust and candy power up cost and gender symbol.
Tested on Nexus 5.
> Add missing non-calibrated standard crop factors

- .travis.yml
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/LevelToken.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonShareHandler.java
- openCVLibrary330/build.gradle
- Fix a bug that made LevelToken crash when formatting the level value to string
- Improve the JSON stat share to include min-max level
> GoIV 4.3.1 bug fixes and improvements

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Data.java
This is an enhanced version of the new level detection algorithm proposed in #841 that solves @sarav half level offset issue.
(cherry picked from commit 56710edbabe707f399b11f624db51113dd362aea)
> Improve level detection algorithm

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/AutoAppraisal.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
Compute the system navigation bar height to better deduce the appraisal text box positioning.
> Fix the appraisal cropping y coordinates

- .travis.yml
- app/build.gradle
- openCVLibrary330/build.gradle
Update target API to 27 and Android Support Library to 27.x.x
> Target Android Oreo 8.1 (API 27)

- .travis.yml
See https://github.com/travis-ci/travis-ci/issues/8874
> Add workaround for Travis build with Android SDK 27

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/updater/DownloadUpdateService.java
- app/src/offline/AndroidManifest.xml
- app/src/online/AndroidManifest.xml
Add missing permission to install packages on Android 25+
Also clean some code in DownloadUpdateService class
> Fix auto updater

- gradle/wrapper/gradle-wrapper.properties
Update gradle to version 4.5
https://docs.gradle.org/4.5/release-notes.html
> Update gradle to 4.5

- app/src/main/res/values-es/strings.xml
Updated the strings of the values-es with the new strings added/changed
> Update ES strings

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/LevelToken.java
First multiply by two and then round it.
> Fix Lvlx2 output when level has .5

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPopupButton.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPreviewPrinter.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ScreenWatcher.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
- app/src/main/java/com/kamron/pogoiv/utils/WindowManagerUtils.java
- app/src/main/res/drawable/iv_button.xml
- app/src/main/res/values/strings.xml
OcrHelper now scans the fast and charged moves names into ScanResult.
IVPopupButton needs to be hidden when a scan is running since it would cover the moveset on most phones.
> OcrHelper: scan moveset

- app/src/main/res/values/integers.xml
Adds the devolution number for wobbaffet to connect the evolution line
> Fixes wynaut detection

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Use the correct Theme to inflate the main overlay layout
> Fix overlay background color

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/IVResultFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/MovesetFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/PowerUpFraction.java
Fix navigation in overlay when "should show confirmation" preference is set to off
> Fix navigation between overlay Fractions

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
If a ScanArea is invalid log the error with Timber so we can have a hint of what's happened then fall back to default crop areas.
> Improve OcrHelper stability

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/MainFragment.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/AppraisalManager.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/MovesetsManager.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ScreenWatcher.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/AppraisalFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
This is a PR made of several bug fixes.
Each commit solves one issue, none of them is too big so it should be easy to review them if taken one by one.
> GoIV 5.0.2 bug fixes

- app/build.gradle
- app/proguard-okhttp3.pro
- build.gradle
Compilation tested for offline, online, playstore with debug and release configurations.
Tested offlineDebug flavor on low-end Android 6.0 device and everything is ok.
> Update Gradle build files and libraries versions

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
Hi GoIV pj. team.
I created a patch for autocomplete view with aloan forms.
Would you check this patch?
> autocomplete view with alolan forms for user input

- app/src/main/res/values/forms.xml
> Fixes alolan diglett stats

- app/src/main/res/values-de/pokemons.xml
for issue #947.
I've checked it can detect eevees evolutions and some alolan forms on German locale system.
> German Pokemon Types

- app/src/main/res/values-fr/pokemons.xml
This PR is for improving to detect pokemons with its type in French.
> French Pokemon Types

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
This PR improves detecting pokemon names text including accent symbol character, like Éevee.
So detecting Eevee and Eeveelutions is expected to be improved in French and others.
> normalizing pokemon name

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/ArcView.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrManualCalibrationActivity.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldResults.java
- app/src/main/res/layout/activity_ocr_calibration_result.xml
- app/src/main/res/layout/activity_ocr_manual_calibration.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
The manual calibration still does not include options for moving the identifier pixels that recognizes if the user is on the pokemon screen, nor the colors the identifier pixels use.
It's ready for some testing though.
> Adds a manual recalibration feature

- app/src/main/res/values/integers.xml
Fix wrong values (zubat or horsea for example) and add missed values in the 3 & 4 generation
> Fix incorrect values and add missed in PokeSpam

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
On my samsung s7, quickIV scan time went from 1.2 seconds to 0.6 seconds, and pressing the IV button went from ~8 seconds to ~2
> Speed optimizations

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
The "new attack" button interferes with scan results, as GoIV misinterprets the new attack cost as evolution cost. The algorithm that checks for the 'new attack' button previously mis-identified pokemon that had evolution item cost requirements as new attack buttons. This should fix that.
> Updates heuristic checking if 'new attack' button is scanned

- app/src/main/res/values/forms.xml
- app/src/main/res/values/integers.xml
Also rearanges forms . xml for  heat and wash form to match the gamemaster json
> Adds mothim devolution to database 

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/ExtendedCpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/ExtendedTokenTierLogic.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/WorthTrainingToken.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/PowerUpFraction.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonBase.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
- app/src/main/java/com/kamron/pogoiv/utils/DevMethods.java
- build.gradle
Also improves how pokemonNameCorrector handles fixing alolan forms
> Changes how pokemon forms and evolutions are stored

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonBase.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
Makes identification use base pokemon instead of candyname
> Fix identification issues related to evolutionline

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/IVResultFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/MovesetFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/PowerUpFraction.java
Buttons were being programmatically set to color.
> Fixed coloration of results tabs

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/AppraisalFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanData.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
- app/src/main/java/com/kamron/pogoiv/widgets/PokemonSpinnerAdapter.java
- app/src/main/res/layout/fraction_input.xml
also makes auto appraisal faster by removing the replacecolors, and fixes that getPokemon and setPokemon were switched out
> Makes auto appraisal update button

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CPPercentageToken.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/IVCombination.java
- app/src/main/res/values/strings.xml
This token is used to show the percentage between 0% and 100% IV.
> Adds a token called CP%.

- app/src/main/res/values/forms.xml
- app/src/main/res/values/integers.xml
Saw that there wasn't an update for Armored Mewtwo yet. Went ahead and updated the XML myself.
> Add Armored Mewtwo Form

- .travis.yml
This fixes execution of Travis CI .. not build result :)
> Upgrade build-tools to avoid CI failure
