- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
This reverts commit [88e93a959b991cd841e086e4e97035ee416830c1](https://github.com/farkam135/GoIV/commit/88e93a959b991cd841e086e4e97035ee416830c1).
> please revert this. It is unnecessary, Android pulls the information from string.xml if e.g. strings-de.xml does not contain the element.
> 
> Also there is a nice translation view where you can see all elements in every language.
> http://tools.android.com/_/rsrc/1408658785758/recent/androidstudio087released/translations4.png
> Revert "Added resources across languages for future translations."

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/pokefly.java
Associating a pokemon and its evolutions was using an O(n^2) algorithm.
For 151 pokemon, that's 22801 iterations! Changing it into O(n)
algorithm. So, the pokemon list population should take less than 1% of
the previous time.
Since every evolution comes after the pokemon in the pokedex, we can
immediately associate the evolved pokemon to its devolution. To do this
the evolution list had to be converted into a Pokemon list. This has
some cascading code change impact, but those make the code more readable
and efficient too (removes a lot of unnecessary int to Pokemon lookups).
> Improve efficiency of evolution tracking

- DEVELOPMENT.md
- README.md
Fix #60. Build instructions should be in the project, somewhere where they are easy to find.
> Add build instructions

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/PoGoApplication.java
- app/src/offline/java/com/kamron/pogoiv/CrashlyticsWrapper.java
- app/src/online/AndroidManifest.xml
- app/src/online/java/com/kamron/pogoiv/CrashlyticsWrapper.java
For those of us that don't like that internet permission 😺 
This PR will also change logging somewhat. All logging should be done through [Timber](https://github.com/JakeWharton/timber) now. The API is very similar to `Log`, you have `Timber.e` and so on. For debug builds all logs go to logcat. For the offline release builds all logs are swallowed. For the online release build all logs go to Crashlytics.
From Android Studio you can choose what variant to build by clicking the 'build variants' tab in the lower left of the IDE and using the dropdown
Not sure how you go about making the `.apk`s for release. I use the command line, doing a `./gradlew clean build` (or `./gradlew clean assembleOnlineRelease assembleOfflineRelease`) will make both `.apk` files. I haven't built a project through …
> added offline flavour that doesn't use the internet permission

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Some of the bitmaps weren't recycled once we are done using them.
Recycle them. The benefits of recycle isn't clear for an app that
targets Android 4.4 and higher, but going with the existing convention
in this project.
Btw, based on what's in [this link](https://developer.android.com/training/displaying-bitmaps/manage-memory.html#inBitmap), looks like calling recycle() might not have any major benefit and using BitmapFactory might be a better option.
> Recycle bitmaps where possible

- app/src/main/res/layout/dialog_info_window.xml
1. Consistent with the navigation back button being on the left
2. Doesn't break the muscle memory for right handed people expecting the
close button on the right side.
> Swap the Close and Back button in the info dialog

- app/proguard-rules.pro
Removed warnings from okio (see this: http://stackoverflow.com/questions/36010942/getting-warnings-with-proguard-with-external-libraries). Those mess with release build and pro guard - I could not make a release version without this fix.
> fix absent clasess warnings for okio

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Based on these pictures (http://imgur.com/a/BRNUP), I was able to calculate that the max angle for the position of the white dot on the level arc is approximately 178.4 degrees, not 180. I tried to fix the code to account for that fact - you can see these magnificent calculations here: 
I replaced 202.04 by 200.00 in the code, deleted these weird -0.5 / +0.5 that were necessary before, and tested it on my phone (Nexus 5, Android 6). It fixed all the alignment problems I had! It probably needs to be tested on more devices, but I'm quite enthusiastic about this change.
> Fix alignment issues with the level arc

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
@sarav pointed out `replaceColors` does lots of floating-point computation: https://github.com/farkam135/GoIV/pull/140#discussion_r75915929
This PR avoids FP computation while giving the same results (unless I screwed up).
Untested—don't merge before review.
> Avoid floating-point ops in replaceColors

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
So, this finally saves the user corrections. So, once the user corrects the Beedrill issue or any of their renamed pokemon, the app should remember them across restarts.
> Preserve user corrections of pokemon name OCR across app launches

- CHANGELOG.md
- README.md
As previously discussed, Added all changelog since 1.3.0. Need to limit on how many changelogs we are keeping, not feasible to keep all changelogs. Maybe maximum of 5?
> Detach CHANGELOG from README

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
Removes unnecessary strings from pre-UI overhaul
Note: Check before doing a refactor, some strings are still being used (Nidoran, screen capture and scan failed strings are used in MainActivity)
> Refactor Unused Strings

- app/src/main/java/com/kamron/pogoiv/Data.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/Pokemon.java
Addresses #182 by deleting either the first or the last word. Also performs a bunch of refactorings, and makes matches on the candy text case-insensitive. Appears to work (even without corrections IIUC).
> Fix Mr. Mime's candy detection & refactor

- app/src/main/java/com/kamron/pogoiv/PokeInfoCalculator.java
The code flipped back and forth. @farkam135 suggested using `||`, I changed it, and @nahojjjen changed it back in cf8ab33a5b7a69693be631137a2c58b5c4d7f9b7. GoIV can give useful info here, especially with narrowing—and even without there's a delay but I find it acceptable.
What do you think?
> Allow processing pokemon without HP=CP=10 (#235)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_results.xml
Added new UI elements to address the single match scenario. This was partially discussed on Issue #217.
The rationale behind it is that if there's a single match there is no need for further refinement, and its just a hassle for the user to tap "See all" to see the one result.
Result values are color coded with the same ratios as the percentages from the IV calculations.
Here's an example of how it looks like:
> Single match layout behaviour

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
the `PreferenceFragment` can do all the saving for us
this can be merged independent of any changes to how settings are accessed
> Remove unnecessary SharedPrefs writes from settings

- app/src/main/java/com/kamron/pogoiv/PoGoApplication.java
- app/src/offline/java/com/kamron/pogoiv/CrashlyticsWrapper.java
- app/src/online/java/com/kamron/pogoiv/CrashlyticsWrapper.java
Static references to context often cause memory leaks. This one was fine but it's better to just not have them (people copy code patterns they see, the next time it mightn't be the application context that's kept around)
> stop keeping a static reference to context in hte crashlytics wrapper

- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
Tesseract allows single-line scan to improve quality. [See wiki] (https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality)
Reference issue [#180] (https://github.com/farkam135/GoIV/issues/180)
> Tweak tess to do single-line scan instead

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Before: getting the settings object would give you a snapshot of settings at that moment in time that did not reflect changes a user would make.
Now the settings object is just a wrapper around shared preferences and will read the most up to date value every time it's requested. The accessor names read a little better now too I think
I made it a singleton because there don't really need to be more than one instances floating about since it's just a read wrapper and it made the refactoring smaller (MainActivity kept a reference to a settings object). I've no strong feelings on if this is nicer than not having an object and using static methods like `GoIvSettings.isAutoUpdateEnabled(context)` wherever you want to check a setting.
> refactor settings so that reads always return the current value

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Before, this was skipped sometimes, leading to duplicated IV values.
This happened when refining, or when going back to the input dialog and
computing IVs again.
> Clear IV possibilities before adding new ones

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/OCRHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/ScreenGrabber.java
- app/src/main/java/com/kamron/pogoiv/ShareHandlerActivity.java
PR is not yet complete. Making a request so people can see the progress and make comments. There are tiny hacks (accessing public variables, making unnecessary dependencies, etc) to keep each commit small enough to review. When the PR is done, most of those hacks should go away.
I'm stuck at the last one because I can't (yet) find the code that makes the (IV) button disappear.
Did some quick tests and it works so far.
This should address #203 -- you can already see how the timer stopping isn't times to some public variable. So, we should at least not get any timer races.
EDIT (by @Blaisorblade): fixes #203 and fixes #234.
> Clean up screen handling code and intent flow

- app/build.gradle
- app/src/test/java/com/kamron/pogoiv/IVCombinationTest.java
This can be run with `./gradlew testOfflineDebugUnitTest` or `./gradlew testOnlineDebugUnitTest`
`./gradlew test` cannot be used because of the crashlyitcs id needed for online release builds
> added a basic unit test

- .idea/codeStyleSettings.xml
Goal: enforce a consistent coding style across contributors.
Because the main thing that matters is consistency, I picked the Android Studio default, which is what I've been already using since ages. Consistency matters, among other things, to have readable diffs.
The only point of contention is whether to break long lines. @sarav is strongly in favor, and @nahojjjen finds it decreases readability. The default coding style does not break long lines. I dislike this default but not strongly.
Questions:
- does this allow a consistent workflow for all? Can we agree to reformat all PRs automatically that way?
Non-questions:
- which coding style is best? People have strong opinions, but the particular coding style matters much less than consistency (source: Code Complete).
WARNING: I reserve …
> Add default IDEA coding style as a project one

- .travis.yml
This PR proposes to add a first form of continuous integration—this ensures that each PR compiles before merging (though doesn't enforce that), both alone and after merging with `master`.
In the future we might also try running some automated tests, but we'd have to add some.
This can only be enabled in Travis by @farkam135 (unless he gives somebody else higher privileges). I've tried out this code in my repository, results are visible in https://travis-ci.org/Blaisorblade/GoIV/builds.
Also, this makes sense if we agree to actually keep the build green.
Fixes #254.
> Add Travis-based continuous integration

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Revert "Warning toast in case of error case or ocr slow
init" (9ac1355ba784d1b85700d110edfd775c8421c377). As discussed in #284,
this null check should be unnecessary; if it is necessary, crashing
might be better than mitigating the bug and hang.
Fix #284.
Don't merge yet since we're apparently still debugging it. Ping @sarav.
> Prevent scanPokemon from hanging the app (#284)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/dialog_input_appraisal.xml
- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
I took #304, merged conflicts, and did a couple refactorings on the new code to reduce copy-pasting. Credits to @nahojjjen and @DJCrapsody for most of the work.
----
Quoting from #304:
As this changes were based on @nahojjjen's fixInfoDialogHeight branch, this PR should supersede https://github.com/farkam135/GoIV/pull/294.
Additional things done:
* Rename "Appraisal narrowing" to "Appraisal Refining"
* Remove "(optional)" as refining is closed by default now
* Fix layout of Appraisal Refining
* Add rotating animation to appraisal refining box arrow
* Change rotating animation to happen before dialog shows/hides
* <s>Fix alignment of Evolution spinner using negative margins</s> (I removed that)
* Fix devolution CP text by checking if result CP is negative
Fixes #272 and fixes #293.
> Fix input dialog and expanded results box, V3

- app/src/main/java/com/kamron/pogoiv/CommonLogger.java
- app/src/offline/java/com/kamron/pogoiv/CrashlyticsWrapper.java
- app/src/online/java/com/kamron/pogoiv/CrashlyticsWrapper.java
This could be helpful to users of offline versions that have problems and try to use logcat on it. @harkin thought this was worth of discussion (and I misunderstood the logic when originally committing), so here's a PR to discuss.
> Send non-Crashlytics logs to logcat at least in releases

- app/src/main/java/com/kamron/pogoiv/GUIUtil.java
- app/src/main/java/com/kamron/pogoiv/PokemonSpinnerAdapter.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/spinner_evolution.xml
Fixes #312.
NINJA EDIT: This PR also reduces main activity numberpicker height as discussed in #273.
I'm summoning @DJCrapsody and @nahojjjen to the discussion.
I gave a look to the code of our spinners and it turns out that we are inflating a single textbox in the adapter. Currently it's the same xml resource that we use to show the selected Pokémon, so they share their settings.
What I do here as a quick fix is to leave the TextView without margins and padding (so it aligns nicely to the right on the advanced information panel) and provide the inflated TextView instance that we use to display as each item in the dropdown with some new properties (padding, text align, gravity), so it shows its contents at the center.
Now, this works, but I'd like to make a sencond pass later and maybe …
> Quick fix for the Pokedex spinner and MainActivity numberpicker display issues

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
Fix #309: auto-accept the trainer level typed in the input screen. Idea
by @oskomonzon.
> Accept level without pressing checkmark (#309)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_results.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
The ATK, DEF, STA and MIN, AVG, MAX strings couldn't be translated, so I tried to change that. Here's how it looks on my phone now, in French: http://imgur.com/a/MNWYf
> Make more strings translatable and update French translation

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Here's a potentail deadlock: If scanning fails we produce and send an
empty intent. Right now if we receive that, we set `receivedInfo` even
though we received no info, so the next button press will be ignored.
Usually the flag would be cleared by closing the input/result
dialogs—but since we're showing none, that's not possible!
IIRC I introduced this, sorry. But finally I found it (I think).
Testing.
> Remove deadlock we had

- .gitignore
- DEVELOPMENT.md
- app/build.gradle
- keystore.properties.sample
I don't know how everyone else generates signed release builds, but I thought this might be helpful.
Please let me know if there is a better way.
> Load credentials from keystore.properties

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/SettingsActivity.java
Fix #315. A bit hacky, but I'm not sure how to change settings from
elsewhere, and where, and we're in a hurry.
And force screenshot mode also for API level 20.
Nobody should be running GoIV on Android Wear IMHO, but there are
unexpected crashes on Android 5 with NoClassDefFoundError for the
MediaProjectionManager API, so let's rule that out more clearly.
> Quickfix manual screenshot mode

- app/build.gradle
- checkstyle/checkstyle-rules.xml
- checkstyle/checkstyle.gradle
Things this does that might be controversial:
120 character line limit (do you care about line limits? I like 120 but will happily change it)
No Hungarian notation. It's awful.
Some rules about javadoc formatting.
Naming of abbreviations: `theOCR` is not allowed, `theOcr` is allowed
There are tonnes of violations currently, I _think_ CI can be configured to allow a certain number so at least more won't creep in
To run: `./gradlew checkstyle`
> Added checkstyle rules and configured checkstyle plugin

- .gitignore
- app/fabric.properties
- app/fabric.properties.sample
- app/src/main/AndroidManifest.xml
This way, adding a fabric key will not require editing the manifest.
@farkam135 I'll merge this soon, you'll have to adapt before next release.
Next step: allow release builds on Travis.
> Release builds: move Fabric keys out of manifest

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanResult.java
Fix #374.
I'm not done on failures for candy recognition though: it seems that code can't fail, so I dropped the current catch block for it as dead code. There's other code depending on that.
> Use Optional for scan failures in HP/CP, avoid defaulting to 10

- .travis.yml
- DEVELOPMENT.md
- GoIVCodeStyle.xml
- checkstyle/checkstyle-rules.xml
Now that I fixed all violations, enable checkstyle on Travis.
* Turn Checkstyle violations into errors.
* Run Checkstyle on Travis.
* Update the uploaded style for Android Studio.
> Prevent checkstyle violations through Travis

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/ScreenGrabber.java
Fix #391.
This reworks branch speedup-screen-check based on discussion in 4de491198c667ba3c1ccb78f8cace24e57b60d00. I ended up doing the refactoring from scratch, but the new code still works and makes sense.
This also changes pokemon-screen detection to bound-check the individual pixels rather than check if the image is in portrait format. I expect this change to be safe.
Review assigned to @sarav.
> Speedup screen check by grabbing only needed pixels, v2

- app/src/main/java/com/kamron/pogoiv/widgets/PlayerTeamAdapter.java
- app/src/main/res/values-fr/strings.xml
I changed the colors of the team picker to match the colors used in the Pokémon Go app, because the Instinct color looked a bit green/weird to me.
I also updated the French localization, following the recent changes made to appraisal in #379. And I moved the Instinct strings below the Valor ones, to match the order of the team picker, because I kept reversing them while editing and testing the translation. It makes the "files changed" tab a bit confusing.
> Change team picker colors + shorten appraisal (fr)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
This addresses #300 
The current implementation scans the screen every 750 milliseconds. This
is pretty expensive in terms of power consumption.
Since the screen mode (map, gym, pokemon, etc) doesn't change unless the
user actually touches the screen, we just need to scan the screen around
the time the screen is touched.
Also, since the user touches the screen a lot during a gym battle, add
some throttling to scan the screen only after the last touch if multiple
touches happen in quick succession (within 750 milliseconds).
This should significantly improve the power.
Since there are some animations which take time when the user opens a
pokemon switches pokemon, scan a couple of times before stopping.
**Caveat:** The touch events only come when the user touches the screen and not when the …
> Power optimization: Scan screen only when user touches it

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
If the user scanns a 10 cp pokemon, the iv scan will simply set a flag
saying "too many iv combinations", because there are 16^3 possible
combinations, and it's not been narrowed down. Clicking the "See all"
button simply takes you to an empty list. This change removes this link.
fixes #376
> Hides "See all" link if tooManyPossibilities set

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
This commit makes the moveOverlayUpOrDownToMatchAppraisalBox method
always move the overlay down if the user is not on the input screen, as
it's not possible to end up in a situation where the appraisal box is
both intended to be expanded and not exist.
Fixes #406
> Overlay gravity only top if on input screen

- CONTRIBUTING.md
Adds a blurb to the contributing doc about the syntax to use in a PR message in order to have GitHub auto-close a related Issue when a PR is merged.
> Add PR message Issue auto-closing info

- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
The evolution spinner shows numbers next to each Pokemon's evolution, so
sorting them alphabetically gives us a strange order for Eevee, which
happens to be `#136 Flareon #135 Jolteon #134 Vaporeon` rather than
ascending order.
> Stop sorting evolutions alphabetically

- app/src/main/java/com/kamron/pogoiv/GuiUtil.java
After much discussion in #336 and #388, no consensus has been reached about which colors to use to highlight IVs on the results screen. However, I propose that we use these red/orange/green/blue colors - http://i.imgur.com/jenqZv5.png - for the following reasons:
- of the few people who gave their opinion about the colors, a (very small) majority prefered the darkgreen/blue combination.
- I think it makes IVs easier to distinguish compared to the colors that are currently used.
- red/orange/green/blue still follows the natural progression of the spectrum of light, so blue feels like it naturally means "better than green".
- I tested 3 color combinations (the one from #336, lightgreen/darkgreen from #388 and the one from this pull request) on a color blindness simulator (Coblis). This PR …
> Change colors for IV highlighting

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Just got an exception here, when sharing through Now on Tap a PoGo
screen without pokemons. I assume this would be triggered by having "/"
as string; I've confirmed that `"/".split("/")` gives indeed an array of
length 0.
```
09-23 02:20:20.758 29581-29581/com.kamron.pogoiv E/AndroidRuntime:
FATAL EXCEPTION: main
Process: com.kamron.pogoiv, PID: 29581
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.kamron.pogoiv.OcrHelper.getPokemonHPFromImg(OcrHelper.java:298)
at com.kamron.pogoiv.OcrHelper.scanPokemon(OcrHelper.java:349)
at com.kamron.pogoiv.Pokefly.scanPokemon(Pokefly.java:1566)
at com.kamron.pogoiv.Pokefly.access$1200(Pokefly.java:82)
at com.kamron.pogoiv.Pokefly$11.onReceive(Pokefly.java:1606)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadca …
```
> OcrHelper: Prevent crash if hpStr = "/"

- build.gradle
Android Studio 2.2.0 has been released and gradle plugin has been updated.
Performance and fixes were done.
More info in [Release Notes](https://developer.android.com/studio/releases/gradle-plugin.html)
Should be updated to as soon as possible.
PR recreated as commit has been moved to a separate branch.
> Update Gradle to 2.2.0

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
If I enable "Don't keep activities" (tested under Android 7 on my Nexus 5X), GoIV dies immediately after going away from the MainActivity, which is to be expected from the description.
This PR fixes the problem, and generally enables GoIV to keep working if Android kills MainActivity (which it can do at will). Conversely, Android will try to keep Pokefly active till possible, because it is considered a foreground (hence important) activity, thanks to our persistent notification (technically, thanks to `startForeground`), according to [relevant docs](https://developer.android.com/reference/android/app/Service.html#ProcessLifecycle).
> Ensure GoIV survives "Don't keep activities"

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Android Studio 2.2 considers this a serious warning and even marks it as
an error. While the code works perfectly fine it's overly general (and
might be inefficient). So let's fix the warning.
> Fix warning/error with String formatting

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/values/strings.xml
This pr adds two new fields in the powerup and evolution box in the results window. HP and %CP vs max iv.
I'm probably not going to add tier to the results, and instead just add it as an option for user configurable clipboard in another pr.
> Add perfection and hp estimates to evolution box

- README.md
First of two things changed is the cache on the badges was 30 days, so they weren't updating even on hard webpage refresh, so I changed the cache to 6 hours for all but the license one.
Second thing is that using the badges as links isn't obvious enough for users visiting this page just to get the latest download and see the changes. The wording is also awkward between what the badge is trying to communicate and what we're trying to say the link we're using the badge for is actually leading to. For example, the wording of what the download number actually was for (total downloads ever), versus the wording that made it seem like just downloads for the current version. Anyways, the result is I moved the badges all up all in-line so we're not relying on them to be the main links and made …
> Cleanup README badges and links

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeSpam.java
- app/src/main/java/com/kamron/pogoiv/logic/ScanResult.java
- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/expanded_results_box.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- app/src/test/java/com/kamron/pogoiv/logic/PokeSpamTest.java
If enabled, compute how many pokemons of the current species can be
evolved with the current amount of candies.
Squashed version of #457 until
7dedc5ed0977e5a5cc0ed676f340a44e1dbc6c80 (excluding the plugin system).
This is just the changes between that commit and
196b638333fb2586ffef60a7a4af91525ed5e504 (the latest commit on master
reflected on that PR).
Open issues:
Closes #457.
> Add PokeSpam calculation

- app/src/main/res/layout/dialog_input.xml
With the adding of PokéSpam, a "Candy" field appeared next to the CP and HP ones in the dialog where you input your Pokémon's info. But the word "Candy" is longer in other languages ("Caramelos" in Spanish, "Bonbons" in French), so there wasn't enough room to input a 4-digits number of candies.
This change is the best way I found to make enough room in every language. Here's what it looks like in Spanish: http://i.imgur.com/dHcGP32.png
and in English: http://i.imgur.com/05HxEdz.png
I left the width of the "candy" field bigger than the CP and HP ones because it allows 5-digits numbers, while CP and HP only allow 4-digits numbers. (I tried to see what it would look like if it was the same width as the two other fields, to be more consistent (http://i.imgur.com/LXEjaSq.png), and I think it …
> Fix sizing of CP/HP/Candy fields in dialog_input for translations

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Renamed PokeSpam strings, Fixes https://github.com/farkam135/GoIV/issues/496.
By the way, speaking of Pokéspam I came up with the name when designing that feature so it will fit that little box. For now its doesn't live exist outside of GoIV, but soon the world!!! [Google Search...](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Pok%C3%A9spam)
> Fix new strings breaking naming pattern

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
`Pokemon.toString()` should just have a cosmetic function (I proposed
changing it in #503). And there's no need for a lookup. The problem is
only that `getSelectedItem` is declared to return `Object` when in fact
it returns `Pokemon` (part of the involved classes have not been
generified yet).
Testing ongoing.
> Avoid using toString in lookup

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
This implementation assumes that the tesseract manages to scan "cp" or
"7p" or something similar, which is at least always two characters.
The reverted implementation removed all non-numerical characters, which
did not always work as sometimes "cp" was scanned as "c9" or similar.
> Reverts change to how scanned cp text is parsed

- app/src/main/java/com/kamron/pogoiv/logic/PokeSpam.java
Small refactor of the `PokeSpam` class. 
Made the constants static and changed to follow the normal naming convention. 
Removed the optional parameter from the second constructor and opted to chain them instead.
> small refactor of PokeSpam

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
Edited description:
The identification method which uses evolution cost and candy name now returns that it's unsure of the pokemon if it detects that the evolution line branches. (This currently only happens for eevee.) Because of this, is continues testing other guessing methods, and these guessing methods take user corrections into account.
edit: fixes #518
> Re-enable user corrections for eeveelutions

- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
I dont think these hardcoded suggestions help the users more than they can potentially annoy users, now with the new identification module.
They're initiated every new restart of goiv
They assume that rainer, pyro and sparky are eevees, not vaporeon, flaroeon and jolteon.
> Removes hardcoded "user" corrections

- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
Hi Team,
This should fix Eevolutions part of #535 
1. https://github.com/farkam135/GoIV/commit/771455b22c5207d3135f89ecd5234425697646ff added get the Pokemon with the closest name within the evolution line (for eevees)
2. https://github.com/farkam135/GoIV/commit/51542c199d14aafe89e15c6c228d5e8b9c324f39 put back user correction during Pokemon check (removed at https://github.com/farkam135/GoIV/pull/531), this does not override user correction.
> Guess eevelotion based on candy

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Hi Team,
below is a check for GOIV screenshot, I was able to scan images from iphone.
code:
```
// this should allow processing of images where the displaymetrics don't match, for example a different
// phone, it is known that the red dot might not display correctly.
if (displayMetrics.heightPixels != bitmap.getHeight() || displayMetrics.widthPixels != bitmap.getWidth()) {
bitmap = Bitmap.createScaledBitmap(bitmap, displayMetrics.widthPixels, displayMetrics.heightPixels,
false);
}
```
Known issues:
Red dot location MIGHT be off if the image height is different
since red dot is based on the screen, and since the photo display software (andorid photos etc.) probably stretches the display to fill width of the screen that red dot might be located elsewhere especially if height of the screen …
> Fixes #463 Crash when scanning screenshot from another device.

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/NpTrainerLevelPickerListener.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
Fixes #504
1. Added stop button to notifcation (if we stopped from notification)
2. Added settings button. (Only when stopped)
3. Removed Open App button (only room for 2 icons), clicking on GoIV notification will open GoIV. (based on android docs we should not have 2 objects do the same thing)
4. added +1 trainer level button as requested in https://github.com/farkam135/GoIV/issues/268 (will only show if GoIV is started)
Known issues:
1. Notification is destroyed then a new one is created:  Notification is tied to service (to make it a foreground service), so when selfstop is fires it will kill the notification. At api 24 stopForeground(STOP_FOREGROUND_DETACH) should fix that but I don't have API 24 to test.
2. if we are in screen capture mode, start button in notification will open the …
> Better notification Start, settings and +1 level  in notification bar

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Hi Team,
below possibly fixes https://github.com/farkam135/GoIV/issues/477 (to address #535), Testing is need, can someone reproduce the bug?
If we have an null intent we throw an error early so we don't need to dig to the log, conversely we can handle nulls for on destroy.
> changed onStartCommand with intent to START_REDELIVER_INTENT, added error for null intent (Testing needed)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
1. Changed plus button to one that is closer color scheme of start button.
2. Added notification sub text "Tap to open GoIV."
3. Naming convention fixes for stings
4. Change visibility to public so notification can be viewed from lock screen
5. Change priority to high, as long as we are the first notification, it will be opened expended (max priority notification are higher priority)
> Minor changes to Notification 

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Close http://crashes.to/s/c99c9d8a9c5. But this might lead to duplicated
assets if the external folder becomes unavailable.
This is a new PR for #421 — I closed that accidentally when I moved the branch to my fork—consider this an issue, we're still not sure this is the correct approach.
> Fix crash when no external storage is available

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
Fixes #551
1. Added **short** toast message in "Center" gravity.
2. Changed default setting to `Name (3 char)` + `Min-Max` + `Unicode not filled (MAX IV)`
3. Removed some debug log messages.
> New Feature to add a toast when text is copied to the clipboard.

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
So that user can see if goiv is running easier.
> Makes notification red when paused

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/layout/dialog_input.xml
1. Clicking on textbox will now have a **working** next and done buttons.
2. All text in EditText will be selected on focus 
3. Renamed enableOrDisablePokeSpamBoxBasedOnSettings to showCandyTextBoxBasedOnSettings
> Add Next and Done to keyboard; select all text on Focus in confirmation screen

- app/src/main/res/values-de/strings.xml
Change German translation based on user @chrisi51 at #567
I don't speak German so I used google translate to check.
before: `Use the slider to align the red point`
after:    `Move the red dot with the slider`
> Change slider prompt to be shorter and consume only 1 line.

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/res/xml/settings.xml
So when the online version is published to google play, the user does
not get two different ways that update the app.
> Sets auto update to false

- app/src/main/res/values/integers.xml
Turns out metapod had an error in it in the dataset i used to copy the stat information.
The dataset has been updated now, and Ive double checked with the formula used to generate the base stats from the game stats.
> Fixes base stat errors that are found from last update

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
In some resolutions tesseract misstakes 8 and 5 as B or S, this fixes
that.
> Fixes scanning 8 or 5 as S or B in hp

- app/build.gradle
We should have done this earlier. Maybe we should update to the next version code directly.
> Bump version for 3.3.1

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/PowerupsToMaxToken.java
For example, a level 30 pokemon has "20" powerups to 40.
> Adds token which lists powerup to lvl40

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Screen shot images are scaled with the image ratio unchanged and additional
height cropped. This way the navigation bar is cropped and the OcrHelper
can find the pokémon information.
> Fixes #563 - screen shot scan error

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
The toast message gets annoying when checking IVs after a day of catching.
The default is still to show the toast like it used to be.
> Add settings to optionally disable clipboard toast

- app/src/main/res/values-zh-rTW/pokemons.xml
Fix scan gen 2 error when language is zh-tw.
Add 152, remove 252
> Fix zhtw pokemon name offset 1

- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/CpPercentileToken.java
* Refactor CpPercentileToken to not unnecessarily perform [Combinatorics](https://en.wikipedia.org/wiki/Composition_%28combinatorics%29) calculations every time - Closes #617
* Rephrase LongDescription - Closes #618
* Fix Preview to return an integer rather than a decimal - Closes #619
> Refactor CpPercentile Token

- app/src/main/res/values/pokemons.xml
Misdreavus was missing the final "s".
Lines 162, 165, 205 & 210 had extra characters outside of the <item></item> tags.
> Fixed spelling of Misdreavus and syntax of XML

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/MixedUnicodeToken.java
- app/src/main/java/com/kamron/pogoiv/logic/IVScanResult.java
The new MixedUnicodeToken is intended to be have exactly as the
original UnicodeToken, except that the filled vs. empty unicode
characters are now used to indicate exact or multiple values for each
stat.
For example, if CheckIV returns multiple results, this token will
look at each stat individually to determine if each one only has 1
possible value or multiple. (ie: Attack 11-12, Defense 9-11, and HP
only has 13 for all combinations... this would result in Attack and
Defense being one unicode character set and HP being the other.
When modifying the clipboard settings, the trainer may select whether
they wish for the "empty" to represent exact values or the "filled"
to represent exact values.
This provides a bit more clarity to the UIV value without adding any
extra characters in the …
> New MixedUnicodeToken for copy to clipboard

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Implements the stopping of the Pokefly service if the user swipes the MainActivity away from the Recent Apps screen.
These changes resolve #631
> Stop pokefly service on destroy of main activity

- app/src/main/res/layout/activity_main.xml
Removing the ability for the numbers within the trainer level picker
from being selected.  Sometimes this would additionally cause the
Android Cut/Copy/Paste menu to appear on screen.
Using blockDescendants prevents the numbers from being selected or
edited directly.
(cherry picked from commit e9d5cf1)
> Prevent trainer level number picker from obtaining focus

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
A screenshot submitted in issue #635 seemed to indicate that some
phones might display the white area of the Pokemon screen in more than
one color of white.  Specifically, that screenshot had #fafafa and #f9f9f9.
Adding the alternative color observed, rgb(249,249,249).
> Add alternate "white" for pixels[0] location

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
Adds in parenthesis to %CP vs max IV how much cp is actually less than max, so for example, if you have a pokemon which will max out at 900 cp, but a perfect iv would max out at 1000, the row would now say:
% CP vs max IV(?)  90.0% (-100)
suggested in #629
> Show diff max cp

- app/src/main/res/values/appraisals.xml
mystic_ivrange2_phrase2 used the word "stats" which shows up multiple
times in other phrases.  Changed to "must" to improve accuracy.
mystic_ivrange4_phrase2 used "opinion" but it appears to have changed
to "estimation" since the appraisal feature was released.
There are 2 other phrases in which no appropriate value can be
selected as a 2nd phrase.  Updating the values to align with the
technique (repeat first phrase/word) and comment style from 
values-de/appraisals.xml
> Fix a few auto appraisal phrases for more accuracy

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
The previously added and merged cancelNotification didn't seem to
work as intended, and caused a GoIV crash when the user pressed the
Back button from the main GoIV screen.  Replaced with a TODO for
further investigation and proper implementation at a later date.
> Remove cancelNotification, add TODO for proper implementation later

- app/src/main/java/com/kamron/pogoiv/AutoAppraisal.java
- app/src/main/res/values/appraisals.xml
Instinct appraisal phrases use the word "best" quite often.  Due to
this, addInfoFromAppraisalText is updated to only try to match
IVRange when appraisalRangeGroup is not already checked. Also change
"best" to "best of" in instinct_percentage1_phrase2.
-- Tested with Instinct account and all matches seem to be accurate now.
In addition, some match-words for Valor are subsets of other words
(strong/strongest, great/greatness).  This change adds a space after
strong and great so as to prevent matching strongest/greatness.
-- Has not actually been tested against a live Valor account yet.
> Refines logic for matching appraisal phrases and updates for Valor/Instinct

- app/src/main/java/com/kamron/pogoiv/MainActivity.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
I don't think the Pokefly service should be killed when the activity is killed. It doesn't work well for mid/low tier phones. It also goes against the general app behavior expectations.
> Service lives

- app/src/main/res/values/integers.xml
Referencing the updated base stats on bulbapedia:
http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Pok%C3%A9mon_GO)
This PR submits the differences noted between the above resource and the latest GoIV stats.
> Base stats update as of 20170217

- app/src/main/res/values/integers.xml
This update links all remaining Gen1->Gen2 evolutions that were previously unlinked due to unknown candy cost to evolve to their Gen2 forms.  Evolution links and candy costs are now updated.
> Link all remaining Gen1->Gen2 evolutions

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
In case the Pokemon data is incomplete, manually settings the Pokemon might result in
a force close.
> Fix crash on manual Pokemon input

- app/src/main/res/layout/dialog_input.xml
- app/src/main/res/layout/dialog_input_appraisal.xml
Padding and Margins of a few key components adjusted so as to reduce
the overall height of the appraisal/input window to ensure that the
"Appraise" option within PokemonGo is visible beneath the Appraisal
Input window.
This is open for further review and discussion as to whether this is the
right way to address this issue.
> Adjust appraisal input window padding to reduce vertical height

- app/src/main/res/values-fr/appraisals.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
I translated the new strings and the appraisals.xml file. I tested auto appraisal in French for team Instinct on multiple Pokémon, and it seems to be working. I couldn't test it for the other teams, but I checked that the checkboxes text was displayed ok.
All the token-related strings still appear in English in the app, so I guess they're still hardcoded, but I translated them anyway.
> Update French translation

- app/src/main/res/values/pokemons.xml
Added "n" for Typhlosion
Added "r" fpr Feraligatr
Fixes #664
> Fix Typhlosion and Feraligatr spelling

- app/src/main/java/com/kamron/pogoiv/AutoAppraisal.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/drawable/highlight_rectangle.xml
- app/src/main/res/layout/dialog_input_appraisal.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
This update aims to provide a refined sequence of events and user
interface cues throughout the AutoAppraisal process.
**Pokefly.onTouch logic order swap**
This change swaps the logical order of events when a user touches
the screen.  The new order is for the app to first check if the
Appraisal dialog window is VISIBLE, and if so, go straight to
the AutoAppraisal.screenTouched() method, bypassing the normal
Pokefly screenScanHandler.  But, if the appraisal dialog is not
visible, proceed to Pokefly screenScanHandler without engaging
AutoAppraisal code.
**AutoAppraisal Rescan if phrase doesn't match.**
This change implements an automatic rescan of the screen if the
AutoAppraisal process is not able to match the scanned phrase.  If
PoGo is still animating the text when the first scan is …
> Enhance AutoAppraisal sequencing and user experience

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/ExtendedCpTierToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/ExtendedTokenTierLogic.java
This pull request adds an experimental CP tier clipboard token, which produces an extremely fine grained evaluation for the Pokémon in the AA (worse) to ZZ (best) range, based on the best estimation among the possible IVs.
Evaluations are weighted automatically against the strongest Pokémon available at its best IV. Such upper bound is computed (once per application execution at most), so it should add no maintenance burden.
The system is meant for those who want to use the Pokémon name as a sorting mean to prioritize training the most promising Pokémons CP-wise. The (maybe counterintuitive) choice of assigning ZZ to the best pokémons is due to the IV measure being lexicographically sorting in the same way (with the notable exception of perfect IV and of single-digit IVs).
[![Build …
> Experimental double-letter CP tier

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/IVSum.java
This very trivial token returns an IV evaluation in the most natural format: two digit number in 00-45. It just operates the sum of the single IV values. Solves the lexicographic sorting issues of the classic IV evaluation in 0-100 (single digit numbers and iv perfect get sorted badly).
> Add new IVSum Token

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
When testing on my samsung galaxy S7 running game tumer (comes
pre-installed, lowers resolution to save battery) the scan fails to read
the evolution cost. This tweaks the numbers so the scan succeeds for
both full & lowered resolution.
> Tweaks color for tesseract preperation

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kamron/pogoiv/updater/DownloadUpdateService.java
- app/src/main/res/xml/provider_paths.xml
Fix Auto-Update for SDK Version 24
[History, Explanation and Solution](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en)
"Summarily, file:// is not allowed to attach with Intent anymore or it will throw FileUriExposedException which may cause your app crash immediately called."
GoIV has been updated as shown from this posting, implementing
FileProvider to work for version 24 and above (and still backwards
compatible with prior versions).
> Fix auto update for android version24

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/WorthTrainingToken.java
This PR implements a new token whose goal is to evaluate how worth is spending stardust on a Pokémon, considering its base stats and its individual values.
Motivation: with the recent updates, CP is much less important than it was before, as gyms are no longer based on it. At the same time, the removal of the 5000 stardust/day bonus for gym holders made stardust an extremely valuable resource, that should be invested very carefully.
The idea is that an average Pokémon with very high IV is a better long-term stardust investment than a strong Pokémon with very low IV. This token weighs the base stats of the Pokémon based on IV, then normalizes them considering the best possible Pokemon (lazely computed at runtime once per execution, no maintenance required in case of new Pokémons or changes …
> Implement a "Worth Training" token

- .travis.yml
Android SDK Build-Tools were updated to version 25.0.0.
This commit adds the required license agreement in Travis
configuration file for that specific version of the component.
Resolves: #711
> Fix missing Travis License Agreement

- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/WorthTrainingToken.java
Because of a small oversight, my previous pull request didn't solve the code style issues completely, sorry for that.
Please merge this, @nahojjjen 
PS: The checkstyle plugin seems not working on Android Studio 2.3.3.
I had to run style checks with `./gradlew checkstyle`. Anyone noticed the same behavior?
> Definitively fix code style in WorthTrainingToken.java

- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/WorthTrainingToken.java
WorthTrainingToken was incorrectly put into the "IV Info" category.
Since it is used for 'mons evaluations, move it into "Evaluation Scores" instead!
> Move WorthTrainingToken to the correct category

- app/src/main/res/values-it/appraisals.xml
The italian auto appraisal uses the **visto** keyword to identify this phrase:
> Le sue statistiche sono senza dubbio le migliori che io abbia mai visto.
But it's also present in this phrase used to define XS mons:
> Accidenti! Questo (_mon name_) è il più piccolo che io abbia mai visto!
Use **senza** instead of **visto** since it's unique.
> Fix ambiguous appraisal keyword

- app/src/main/java/com/kamron/pogoiv/clipboard/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/IVPercentageToken.java
- app/src/main/java/com/kamron/pogoiv/clipboard/tokens/IVPercentageTokenMode.java
This is a proposed solution for #717.
Three more IV% tokens get added to the grid, so it clutters the ClipboardModifierActivity.
I'm open to suggestions on how to improve this!
> Add superscript number support to IVPercentageToken

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Sometimes the CP acronym get scanned as one character instead of two.
This can can lead to the trimming of the first digit of the 'mon CP
value since the code always strips the first two starting characters
from the OCR'd text in order to remove the CP acronym.
This commit introduces the ability to detect the container rectangle of
each character inside the CP cropped image. After that, it ignores all
the characters whose height is lower than the average.
This method effectively detects the CP acronym, regardless of the user
locale and it being suffix or postfix to the value, since it's always
written in a smaller font size.
Resolves: #708
> Improve the CP value detection

- app/src/main/java/com/kamron/pogoiv/OcrHelper.java
Hi, GoIV project team.
I try and test to use GoIV for Japanese Pokémon GO game app.
https://github.com/udnp/GoIV_JP
This PR is one of some tips I noticed for OCR multilingualization,
used Nidoran name from resource string instead of hard coded.
(see also https://github.com/farkam135/GoIV/pull/716)
If judging Nidoran name with hard coded value "nidora",
it is failed for other language Nidoran name , like Japanese name "ニドラン".  
So this PR changed to use Nidoran name from resource string, instead of hard coded value.
Could you check this?
Thanks.
> Fix hard coded Nidoran name for OCR multilingualization (updated)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/logic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/logic/PokemonNameCorrector.java
- app/src/main/res/values-it/pokemons.xml
- app/src/main/res/values/pokemons.xml
Hi GoIV team.
This PR fixes hard coded pokemon type names for eeveelution correction.
So eeveelution correction is able to work on non English language also.
This is tested on English and Italiano (and my local Japanese fork build).
But now, to work this fix on other languages(eg de, fr,...),
you have to add localized pokemon type names to your locale `pokemons.xml`,
[like Italiano(it) in this patch](https://github.com/farkam135/GoIV/compare/master...udnp:pr/m17n-eeveelution-correction?expand=1#diff-5c3da1c320986525d8e5971ffde60920).
It seems that eeveelution correction sometimes fails in my test emvironment.
But it is because pokemon type OCR result is wrong(eg `PS**Y**CHIC` is `PS**V**CHIC`).
So I think this problem is caused by OCR error, not by my this PR.
Could you check this? …
> Fix hard coded pokemon type names for eeveelution correction

- app/build.gradle
- app/src/dogfood/java/com/kamron/pogoiv/CrashlyticsWrapper.java
- app/src/dogfood/java/com/kamron/pogoiv/updater/AppUpdateUtil.java
This commit adds a new build flavor that can be used to build internal
releases for developers and testers.
Having a dedicate flavor with a different package name allow us to
install multiple flavors on a single device at the same time.
> Introduce dogfood flavor

- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
Currently running `./gradlew clean assembleOfflineRelease` is throwing with this error: 
```
/Users/lark/src/GoIV/app/src/main/res/values-fr/strings.xml:198: Error: "notification_title_increment_level" is translated here but not found in default locale [ExtraTranslation]
<string name="notification_title_increment_level">Niveau +1</string>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lark/src/GoIV/app/src/main/res/values-it/strings.xml:185: Also translated here
Explanation for issues of type "ExtraTranslation":
If a string appears in a specific language translation file, but there is
no corresponding string in the default locale, then this string is probably
unused. (It's technically possible that your application is only intended
to run in a specific locale, but it's still a good idea …
```
> fix vital lint errors in release builds by removing unused strings

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
The method `removeFirstOrLastWord` needs the whitespace that divide the 'mon family name from the "candy" word to split the input string and pick the 'mon family name.
A regression introduced in 154ffb0322eccaf319e9549b6853ee4dada94adc also removes whitespaces in the middle of the detected text, making it impossible to correctly detetect the candy name.
> Fix regression on candy name detection due to incorrect whitespace replacement

- app/src/main/res/layout/notification_pokefly_paused.xml
- app/src/main/res/layout/notification_pokefly_paused_expanded.xml
- app/src/main/res/layout/notification_pokefly_started.xml
- app/src/main/res/layout/notification_pokefly_started_expanded.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values-v24/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Fix for newer Android versions (5.0+).
Better paddings and no background color.
Please merge this asap so I can push a fix for a crash of CreditsActivity on Android 4.4, thanks!
> Improve notification layout

- app/src/main/res/layout/activity_ocr_calibration_result.xml
fixed distorted text in buttons induced for padding properties
left: distorted text | right: text correctly centered
> Fixed distorted text in buttons of OcrcalibrationResult

- app/src/main/java/com/kamron/pogoiv/PoGoApplication.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/OcrCalibrationResultActivity.java
- app/src/main/java/com/kamron/pogoiv/utils/CommonLogger.java
- app/src/main/java/com/kamron/pogoiv/utils/CopyUtils.java
- app/src/main/java/com/kamron/pogoiv/utils/DevMethods.java
- app/src/main/java/com/kamron/pogoiv/utils/FontsOverride.java
- app/src/main/java/com/kamron/pogoiv/utils/GuiUtil.java
- app/src/main/java/com/kamron/pogoiv/utils/MediaStoreUtils.java
- app/src/main/java/com/kamron/pogoiv/widgets/PokemonSpinnerAdapter.java
- app/src/main/java/com/kamron/pogoiv/widgets/recyclerviews/adapters/IVResultsAdapter.java
- app/src/offline/java/com/kamron/pogoiv/CrashlyticsWrapper.java
- app/src/online/java/com/kamron/pogoiv/CrashlyticsWrapper.java
This move some utility classes to a separate sub-package and save the failed calibration screenshots uncompressed.
> Fix media store compression

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/res/values/strings.xml
When the user drags the level slider in the estimate box, now the cp vs max iv will show the IV for each level, instead of only level 40.
> Makes cp vs max iv update per level

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
When the background of the pokemon is white, or the pokemon overlaps the dot and is white, the "level up dot" can appear to the program to go out of screen, as it cannot find the edge.
> Fixes crash on out-of-bounds level dot check

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPopupButton.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ScreenWatcher.java
Use correct window type for overlays to avoid crashes when targeting Oreo.
See https://developer.android.com/about/versions/oreo/android-8.0-changes.html#cwt
Please merge immediately after #790.
> Fix crash when targeting Android Oreo (API 26)

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
bitmap.recycle is only needed on android 3 and below, in later android versions, bitmaps are correctly handled automatically by the java garbage collector.
> Remove unnecessary bitmap.recycle() calls

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Data.java
niantic changed the maximum level for pokemon from trainer level + 1.5 to +2. I have changed the maximum in the code to 2, but that caused all arc-positions to be slightly off, so i removed a magic '+1' I did not understand why it was in the code. It might have been an undocumented off-by-one fix that is no longer relevant?
Test apk for this change here:
https://drive.google.com/open?id=1p31CzvFfNsGaByfQgbrHD7VL5Nps6UXl
(link will be removed if this is merged.)
> Attempts to fix the +2 level bug

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Data.java
In the input screen, you can now drag the level bar up to 40, regardless of what level you are. This change is introduced since weather catches makes it more common to catch pokemon that are higher level than you're supposed to be able to own.
This PR is based on the +2 level bug branch, if that one doesnt get accepted, ill remake this PR. Im doing this to avoid merge conflicts.
> Weather level pokemon

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPopupButton.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPreviewPrinter.java
- app/src/main/res/values/preview_button_colors.xml
Button now shows "?" instead of toasting an error message when pokemon could not be scanned.
Also fixed some formating issues with the button caused by the buttonreset not covering all aspects.
> Changes !"quickscan failed" toast to button look

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanFieldAutomaticLocator.java
The Y coordinate was offset to the top of half of the arc stroke width.
This should fix half level detection issues.
> Improve level arc calibration

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/PokemonGenderToken.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/AutoAppraisal.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPreviewPrinter.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/IVScanResult.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanContainer.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
Use scanned pokemon gender to better identify Nidoran♀ and Nidoran♂.
Use new Pokemon.Gender enum (values M, F, N) instead of Optional<String> to represent gender information.
Fixes #750 and #812
> Improve Nidoran gender detection

- app/src/main/res/color/goiv_btn_colored_borderless_text_material.xml
Remove an attribute that made the app crash when inflating borderless Button on Android < 23.
> Do not use alpha attribute since it's not supported on API < 23

- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
This PR moves out some Pokefly methods into PokeInfoCalculator since they were only used by the latter.
This gave me the ability to cleanup and simplify Pokefly, refactor PokeInfoCalculator constructors and make some minor improvements to the moved methods implementations.
This PR does not change any PokeInfoCalculator functionality.
> PokeInfoCalculator refactoring and Pokefly code cleaning

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardTokenCollection.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/CpPercentileToken.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/IVPercentageToPerfectionToken.java
- app/src/main/res/values/strings.xml
As requested on Discord #dev channel, add a token that tells you how much your pokémon max IV combination differs from the perfection in percentage.
Since it's made for sorting purposes, adds leading zeroes if the result is lower than 10.
I.e. on a 93% IV pokemon results 07.
Also correct a small imprecision in CpPercentileToken.
> Percentage to perfection clipboard token

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/java/com/kamron/pogoiv/Pokefly.java
- app/src/main/java/com/kamron/pogoiv/activities/ClipboardModifierActivity.java
- app/src/main/java/com/kamron/pogoiv/activities/ClipboardModifierFragment.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardResultMode.java
- app/src/main/java/com/kamron/pogoiv/clipboardlogic/ClipboardTokenHandler.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- checkstyle/checkstyle-rules.xml
I've added an extra clipboard copy format for monsters which have perfect IV's, as I find showing both the percentage and the individual IV's a bit redundant.
- Add a ClipboardResultMode enum to differentiate between clipboard copy
modes. This replaces the singleResultMode boolean
- Add extra tab so the user can configure a format for monsters with
perfect IV's
- Change the logic which determines which clipboard result mode to use
- Removed maxLineLength property from LeftCurly Checkstyle rule, it is
no longer valid
- Small improvements in JavaDoc as suggested by Checkstyle
> Add extra copy to clipboard format for monsters with perfect IV's

- app/src/main/res/values/integers.xml
Stats in latest gamemaster (extracted today)
item_templates {
template_id: "V0384_POKEMON_RAYQUAZA"
pokemon_settings {
pokemon_id: 384
model_scale: 0.57
type: POKEMON_TYPE_DRAGON
type_2: POKEMON_TYPE_FLYING
camera {
disk_radius_m: 0.555
cylinder_radius_m: 2
cylinder_height_m: 3.5
cylinder_ground_m: 1
shoulder_mode_scale: 0.5
}
encounter {
base_capture_rate: 0.02
base_flee_rate: 0.01
collision_radius_m: 1
collision_height_m: 3
collision_head_radius_m: 0.25
movement_timer_s: 11
jump_time_s: 1.1
attack_timer_s: 20
attack_probability: 0.1
dodge_probability: 0.15
dodge_duration_s: 1
dodge_distance: 1
camera_distance: 6
min_pokemon_action_frequency_s: 0.2
max_pokemon_action_frequency_s: 1.6
}
stats {
base_stamina: 191
base_attack: 284
base_defense: 170
}
> Update Rayquaza stats

- app/src/main/java/com/kamron/pogoiv/GoIVSettings.java
- app/src/main/res/xml/settings.xml
Pokespam is now off by default - It's a useful feature, but its also confusing for users to see candy # as input if they dont know about the feature, and it clutters up the UI.
Appraisal expand by default was an option that was set to open by default when the two views were not yet  divided into two different panels. The setting used to make both panels visible, but now it no longer makes sense.
> Change default setting false for pokespam and appraisalexpand

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/InputFraction.java
- app/src/main/java/com/kamron/pogoiv/utils/LevelRange.java
Allow to input pokemon levels higher than the current maximum allowed for the user's trainer level
> Fix InputFraction pokemon level seek bar max value

- app/src/main/java/com/kamron/pogoiv/scanlogic/CPRange.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
Fix a copy-paste error from 2 years ago that made the HP estimation always compute the HP with the highest possible stamina, with some other minor cleanups
> Fix HP prediction when there are multiple possible IV combinations

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/IVPopupButton.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanResult.java
- app/src/main/res/values-de/pokemons.xml
- app/src/main/res/values-fr/pokemons.xml
- app/src/main/res/values/forms.xml
- app/src/main/res/values/integers.xml
- app/src/main/res/values/pokemons.xml
This is #926 , but fixed to avoid merge conflicts. Sorry udnp
> Changes the structure for alolan database

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanData.java
Replaces characters like ó to o, when checking types. So dragón is returned as dragon.
> Ignore special characters in pokemon types, such as ó, read it as o.

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
Hi GoIV pj team.
I've found there is a problem in the v5.0.8 (in my previous patch).
The problem is that a pokemon evolutions list is not correct in the input dialog if alolan forms included, like following.
I've detected the reason, and created a patch to fix this problem.
Would you check this?
> fix pokemon evolutions list in the input dialog

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/ScanArea.java
- app/src/main/res/values/strings.xml
Added an alternate version of the region scan computation which can offset vertically for lucky pokemon. Retained the existing signature for backward compatibility, as well as for use in fields unaffected by lucky status. When the first scannable area that would be affected by Lucky is encountered, if no result is returned, it will retry with the lucky offset; if this returns a value, the pokemon is assumed to be lucky, and further scans below the line will be similarly offset. Using an offset of 120% of the power up candy scan height, just as a "feels right" value. Needs testing against other devices. Works spot on for Pixel.
> Support for changing scan areas for Lucky Pokemon

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanData.java
This PR is a minor improvement for Latin characters (but critical fix for the other characters...)
because in non Latin characters the needed characters  to detect Pokemon name are removed.
It should be better that the "combining characters" are removed instead of non ascii characters.
https://en.wikipedia.org/wiki/Combining_character
> fixed the issue that needed non-ascii charactors are removed

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/Pokemon.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/ScanData.java
- app/src/main/java/com/kamron/pogoiv/utils/StringUtils.java
- app/src/main/res/values-de/pokemons.xml
- app/src/main/res/values-es/pokemons.xml
- app/src/main/res/values-fr/pokemons.xml
- app/src/main/res/values-it/pokemons.xml
- app/src/main/res/values/pokemons.xml
This PRs points are
* normalized pokemon type strings are cached in PokeInfoCalculator instance at first.
* enum Pokemon.Type values are used instead of hard numbers
Next steps, this StringUtils#normalize() is used for pokemon names and candy word, to improve pokemon detection in German and French.
> improvement for normalizing pokemon type

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
- app/src/main/res/values-de/strings.xml
The candy text phrase like "Pikachu Candy" does not have white space separator between the candy word and pokemon name, in the case of some locale languages.
For example, "Pikachu-Bonbon" in German, or "ピカチュウのアメ" in Japanese.
So it is better to detect candy pokemon name with using the localized candy word in the resource strings like "Candy", "Bonbon", "Caramelos", etc instead of white space character.
This PR improves to detect pokemons with their candy names, like pokemons nicknamed by users, especially in German locale.
> improvement for candy pokemon name

- app/src/main/java/com/kamron/pogoiv/scanlogic/MovesetData.java
The Ci step in Travis is failing on checkstyle all the time.
The biggest culprit is src/main/java/com/kamron/pogoiv/thirdparty/pokebattler/PokemonId.java with 2464 style violations. MovesetData was in at #3, I've fixed them all.
Some indentation and whitespacing issues were causing the errors here
> fix checkstyle issues in MovesetData

- app/src/main/java/com/kamron/pogoiv/activities/OcrManualCalibrationActivity.java
The Ci step in Travis is failing on checkstyle all the time.
The biggest culprit is `src/main/java/com/kamron/pogoiv/thirdparty/pokebattler/PokemonId.java` with 2464 style violations. `OcrManualCalibrationActivity` was in at #2, I've fixed them all. 
I'll clean up the other files with style violations, thinking it might be worth adding a checkstyle suppression for PokemonId.java so that CI turns green 
It was mostly whitespace issues, one line length and two for each variable declaration going on it's own line.
> fix checkstyle issues in OcrManualCalibrationActivity

- openCVLibrary330/src/main/AndroidManifest.xml
Splitting out part of https://github.com/farkam135/GoIV/pull/1000/files
There aren't doing anything here and are actually different to the values specified in the `build.gradle` file for this project [see here!](https://github.com/harkin/GoIV/blob/5a2206ab270bdf3810f288853c4e74ed9b525881/openCVLibrary330/build.gradle#L8-L9)
At some point in the compilation the values from the `build.gradle` get inserted into the manifest. Here's the debug manifest generated during a build for me:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="org.opencv"
android:versionCode="3300"
android:versionName="3.3.0" >
<uses-sdk
android:minSdkVersion="19"
android:targetSdkVersion="27" />
</manifest>
```
> remove the android min and target sdk attributes from the manifest in the CV library

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/res/values-de/pokemons.xml
- app/src/main/res/values-fr/pokemons.xml
- app/src/main/res/values-zh-rTW/pokemons.xml
- app/src/main/res/values/pokemons.xml
This is a quick hardcoded patch.
but dose not need to change `integers.xml` and its generator.
tested with a pokemon renamed as Meltan,
because I still don't have these new pokemons.
> detection for pokemons Meltan and Melmetal (quick hardcoded patch)

- app/src/main/java/com/kamron/pogoiv/clipboardlogic/tokens/MixedUnicodeToken.java
This PR addresses https://github.com/farkam135/GoIV/issues/1016, which has also been discussed on Reddit: https://www.reddit.com/r/GoIV/comments/a0u2yo/problem_with_uivmixed07_display_of_calculated/
It fixes the returnvalue to be in line with the description in the app GoIV, which states that it returns the lowest value for each stat. Instead, it currently returns the lowest IV combination.
> MixedUnicodeToken: Returnvalue now matches token description in GoIV

- app/src/main/res/values/forms.xml
- app/src/main/res/values/integers.xml
Some pokemons do not have their evolution pokemon in the [POWER UP] view, like following screen image.
Chingling, Munchlax, Finneon, and Mantyke have this issue reported like following:
https://www.reddit.com/r/GoIV/comments/abrket/no_powerup_prediction_for_munchlax_snorlax/
Additionally, fix the issue that Mantyke with user nickname can not be detected.
> Fix some pokemons evolutionlines

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
Instead of blindly looking at the number in the 'evolve cost spot', we first check if its actually a 'new attack' button, which just happens to be there because it's already a max evolved pokemon.
> Checks if wrongly scanning new attack button before parsing

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
If the evolution candy cost is absent, it throughs an exception if it is
read the first time. And that could happen if a Marill family pokemon
was scanned. In that case it should assume that the cost isn't present.
Fixes: #1043
> Prevent exception when the candy cost is absent

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java
The 'allblank' method heuristic was too trigger happy, in some instances, a few black pixels would accidentally be left in the candy-image, which should still be ignored. This adds a percentage barrier.
I made this patch because a friend couldnt scan pokemon on her phone, and got to borrow her phone and debug to see what happened, which led me to discover this issue.
> Improves mid-evolution detection by removing misdetect

- app/src/main/res/values-de/strings.xml
For some reason two translations in German did have explicit (escaped) quotes, which shouldn't be shown.
> Removed explicit quotes in two German translations

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
When calculating the candy cost for evolutions, it checks that the start pokemon is really before the end pokemon. But with the split of `PokemonBase` and `Pokemon` a typo crept in, which actually checks the devolutions of the start pokemon.
This rewrites it into a simpler function, we already go through the devolutions anyway, so just have one loop which goes from the end pokemon to every devolution pokemon. If the start pokemon wasn't seen until there are no devolutions anymore, it either means that start and end are the wrong way around or that both aren't related.
> Fix evolution candy cost calculation

- app/src/main/res/values/forms.xml
With the change to PokemonBase and Pokemon, pokemons with forms only use the form attributes, which were wrong for those two pokemon.
> Fix form attributes for Unown and Spinda

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- openCVLibrary330/build.gradle
The GoIV Android Studio project is using outdated plugins and build tools.
Update them to maximize compatibility with latest Android releases.
PS:
Yes, the removal of the buildTool lines from the Gradle build files is intended since it is not neened in latest Android Studio releases, the build tools version is inferred from other project properties.
> Update project to Android Studio 3.4.1

- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/AppraisalManager.java
- app/src/main/java/com/kamron/pogoiv/pokeflycomponents/fractions/AppraisalFraction.java
- app/src/main/res/layout/fraction_appraisal.xml
Primarily it does fix the issue that the size of the appraisal box is not fixed to the relations of the screen. So it now does measure the box by scanning the white lines.
Additionally this also contains a few improvements like:
- Don't disable the seekbars
- Check the checkbox when using the seekbars
- Only highlight it while actually scanning
- Actually count the number of retries, so that it could actually "cancel" an appraisal
> Fix appraisal measurement and other improvements

- app/src/main/java/com/kamron/pogoiv/scanlogic/PokeInfoCalculator.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonBase.java
- app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java
- app/src/main/res/values-de/pokemons.xml
- app/src/main/res/values-fr/pokemons.xml
- app/src/main/res/values-zh-rTW/pokemons.xml
- app/src/main/res/values/forms.xml
- app/src/main/res/values/integers.xml
- app/src/main/res/values/pokemons.xml
This PR provides pokemon database update including Galarian, and detection for them.
Galarians evolution line are more complex than Alolans. I think it is better to implement using GAMEMASTER properties about evolution(e.g. `evolutionBranch`) than https://github.com/farkam135/GoIV/commit/02b54d9196aa39ea7d40202977d8d5b0720a8dba#diff-2479e0a9277cb38d3909c0016c11d120. 
So this PR logic should be improved in the future.
> Galarian Pokemons
